server:
  port: 5454

spring:
  application:
    name: trading

  datasource:
    url: jdbc:mysql://localhost:3306/trading_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # options: create, create-drop, update, validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

paymob:
  api-key: ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRBM09UQTBOeXdpYm1GdFpTSTZJbWx1YVhScFlXd2lmUS5IV1NJRVdUZ1ZoaDVvQmZ1OE1tR29TMUszUnFVN0VSMmNoUnBSNGNEQ3EwUjVfclVVdlktT0JhRGxmeThvcmY2RC02bzRyOWRhWGllcVlhbFRFZWhZdw==
  integration-id: 5307448
  iframe-id: 963229
  base-url: https://accept.paymob.com/api

stripe:
  api:
    key: sk_test_1234567890abcdef

razorpay:
  api:
    key: rzp_test_BbLwKBVuQvM5Zt
    secret: KFtSHEnlN03BddjweGF6UsN1

